apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-nginx-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/root/aws-argocd-gitlab.git
    targetRevision: main
    path: react-nginx-argocd/deploy/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: web-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
