apiVersion: v1
kind: Service
metadata:
  name: react-nginx
  labels:
    app: react-nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: react-nginx
  ports:
    - name: http
      port: 80
      targetPort: http
  type: LoadBalancer
