apiVersion: v1
kind: Secret
metadata:
  name: gitlab-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: http://gitlab-webservice-default.gitlab.svc.cluster.local:8181
  username: root
  password: glpat-ilHY6Kw7tdd56NL74QcW1286MQp1OjMH.01.0w0trbfb1
  insecure: "true"